"""Logical error-rate and threshold-style collection APIs."""

from faultscope.collection._collect import (
    Collector,
    collect,
    collect_hotspots,
    iter_collect,
    iter_progress,
)
from faultscope.collection._types import (
    COLLECTION_COUNTER_SCHEMA_VERSION,
    COLLECTION_CSV_FIELDS,
    COLLECTION_CSV_HEADER,
    CollectionCounterSchema,
    CollectionData,
    CollectionOptions,
    CollectionRunOptions,
    CollectionTask,
    HotspotCollectionResult,
    Progress,
    TaskStats,
    read_stats_from_csv_files,
    write_stats_to_csv_file,
)
from faultscope.collection.threshold import (
    FiniteSizeScalingFit,
    PairwiseCrossing,
    ThresholdAnalysisResult,
    ThresholdEstimate,
    ThresholdPoint,
    analyze_thresholds,
    plot_threshold_analysis,
)

__all__ = [
    "COLLECTION_COUNTER_SCHEMA_VERSION",
    "COLLECTION_CSV_FIELDS",
    "COLLECTION_CSV_HEADER",
    "CollectionCounterSchema",
    "CollectionData",
    "Collector",
    "CollectionOptions",
    "CollectionRunOptions",
    "CollectionTask",
    "HotspotCollectionResult",
    "Progress",
    "TaskStats",
    "collect",
    "collect_hotspots",
    "iter_collect",
    "iter_progress",
    "read_stats_from_csv_files",
    "write_stats_to_csv_file",
    "FiniteSizeScalingFit",
    "PairwiseCrossing",
    "ThresholdAnalysisResult",
    "ThresholdEstimate",
    "ThresholdPoint",
    "analyze_thresholds",
    "plot_threshold_analysis",
]
