[package]
name = "faultscope-fusion-blossom-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Experimental fusion-blossom decoder plugin for FaultScope"
publish = false

[lib]
name = "faultscope_fusion_blossom_native"
crate-type = ["cdylib"]
test = false

[dependencies]
fusion-blossom = { git = "https://github.com/yuewuo/fusion-blossom.git", rev = "c536a4bdfb13e5e84ea643213510462306c9cb0f", default-features = false, features = ["disable_visualizer", "remove_blossom_v", "u32_index"] }
faultscope-core = { version = "0.2.5", path = "../../crates/faultscope-core" }
pyo3 = { version = "0.23", features = ["extension-module", "abi3-py310"] }
