"""Forward noise-aware stabilizer trajectory simulator."""

from faultscope.runtime import (
    FaultScopeSimulator,
    SampleBatch,
    UnsupportedBatchCircuitError,
)
from faultscope.core import Circuit, NoiseLocation, Operation
from faultscope.dem import (
    BinaryLinearDecodingProblem,
    Detector,
    DetectorErrorEdge,
    DetectorErrorModel,
    DetectorErrorModelGenerator,
    DetectorGraphEdgeHotspot,
    DetectorGraphHotspots,
    GraphlikeDecodingProblem,
    IndexedDem,
    LogicalObservable,
    SparseBinaryMatrix,
    UnsupportedDemCircuitError,
)
from faultscope.dem import (
    DemHotspotEstimator,
    DemSampleBatch,
    DemEdgeHotspot,
    DemHotspotEstimate,
    DemLocationHotspot,
    DemLocationMetadata,
)
from faultscope.core import (
    BernoulliPauliNoise,
    MeasurementBitFlip,
    PauliChannel,
    SingleQubitDepolarizing,
    TwoQubitDepolarizing,
)
from faultscope.runtime import (
    NativeDemGenerator,
    NativeDemSampler,
    NativePackedSampler,
    UnsupportedNativeCircuitError,
    compile_native_dem_generator,
    compile_native_dem_sampler,
    compile_native_dem_sampler_from_circuit,
    compile_native_sampler,
    generate_native_dem,
)
from faultscope.decoders import (
    NativeBatchDecoder,
    NativeBposdDecoder,
    NativeDecoderBackendUnavailable,
    NativeFusionBlossomDecoder,
    NativeGraphlikeDetectorCopyDecoder,
    NativeNoCorrectionDecoder,
    NativePyMatchingDecoder,
    PyMatchingDecoder,
    PyMatchingUnavailableError,
    UnsupportedPyMatchingDemError,
    available_native_decoders,
    create_native_decoder,
    get_native_decoder_class,
)
from faultscope.runtime import FaultHotspot, FailureEstimate
from faultscope.io import StimImportError, StimImportResult, load_stim_file, parse_stim_circuit
from faultscope.viz import (
    VisualizationUnavailableError,
    write_rotated_surface_code_spatial_hotspot_map,
    write_repetition_gate_structure_hotspot_map,
    write_repetition_hotspot_heatmap,
)

__all__ = [
    "BernoulliPauliNoise",
    "FaultScopeSimulator",
    "SampleBatch",
    "BinaryLinearDecodingProblem",
    "Circuit",
    "DemHotspotEstimator",
    "DemSampleBatch",
    "DemEdgeHotspot",
    "DemHotspotEstimate",
    "DemLocationHotspot",
    "DemLocationMetadata",
    "Detector",
    "DetectorErrorEdge",
    "DetectorErrorModel",
    "DetectorErrorModelGenerator",
    "DetectorGraphEdgeHotspot",
    "DetectorGraphHotspots",
    "GraphlikeDecodingProblem",
    "FaultHotspot",
    "IndexedDem",
    "LogicalObservable",
    "MeasurementBitFlip",
    "NativeBatchDecoder",
    "NativeBposdDecoder",
    "NativeDecoderBackendUnavailable",
    "NativeFusionBlossomDecoder",
    "NativeDemSampler",
    "NativeDemGenerator",
    "NativeGraphlikeDetectorCopyDecoder",
    "NativeNoCorrectionDecoder",
    "NativePackedSampler",
    "NativePyMatchingDecoder",
    "NoiseLocation",
    "Operation",
    "PauliChannel",
    "PyMatchingDecoder",
    "PyMatchingUnavailableError",
    "FailureEstimate",
    "SingleQubitDepolarizing",
    "SparseBinaryMatrix",
    "StimImportError",
    "StimImportResult",
    "TwoQubitDepolarizing",
    "UnsupportedBatchCircuitError",
    "UnsupportedDemCircuitError",
    "UnsupportedNativeCircuitError",
    "UnsupportedPyMatchingDemError",
    "VisualizationUnavailableError",
    "available_native_decoders",
    "compile_native_dem_generator",
    "compile_native_dem_sampler",
    "compile_native_dem_sampler_from_circuit",
    "compile_native_sampler",
    "create_native_decoder",
    "generate_native_dem",
    "get_native_decoder_class",
    "load_stim_file",
    "parse_stim_circuit",
    "write_rotated_surface_code_spatial_hotspot_map",
    "write_repetition_gate_structure_hotspot_map",
    "write_repetition_hotspot_heatmap",
]
