from typing import Any, final
from typing_extensions import Never, Self

@final
class BernoulliPauliNoise:
    def __new__(cls, /, pauli: Any) -> Self: ...
    def apply(self, /, event: Any, state: Any, frame: Any, qubits: Any) -> Any: ...
    @property
    def pauli(self) -> Any: ...
    def sample(self, /, rng: Any, rate: Any) -> Any: ...
    def score(self, /, event: Any, rate: Any) -> Any: ...

@final
class BinaryLinearDecodingProblem:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def dem_edge_indices(self) -> Any: ...
    @property
    def detector_coords(self) -> Any: ...
    @property
    def detector_count(self) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    @property
    def edge_summary(self) -> Any: ...
    @property
    def f(self) -> Any: ...
    @property
    def h(self) -> Any: ...
    @property
    def log_likelihood_ratios(self) -> Any: ...
    @property
    def observable_count(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def probabilities(self) -> Any: ...

@final
class Circuit:
    def __new__(cls, /, n_qubits: Any, operations: Any) -> Self: ...
    @property
    def n_qubits(self) -> Any: ...
    def noise_locations(self, /) -> Any: ...
    @property
    def operations(self) -> Any: ...

@final
class DemEdgeHotspot:
    def __new__(cls, /, edge_index: Any, location_id: Any, event: Any, probability: Any, detectors: Any, observables: Any, sensitivity: Any, hotspot: Any) -> Self: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def edge_index(self) -> Any: ...
    @property
    def event(self) -> Any: ...
    @property
    def hotspot(self) -> Any: ...
    @property
    def location_id(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def probability(self) -> Any: ...
    @property
    def sensitivity(self) -> Any: ...

@final
class DemFaultScopeSimulator:
    def __new__(cls, /, circuit: Any, *, detectors: Any = None, observables: Any = None, approximate_disjoint_errors: Any = 0.0, materialize_dem: Any = True) -> Self: ...
    @property
    def circuit(self) -> Any: ...
    @property
    def dem(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    def estimate(self, /, *, shots: Any, seed: Any = None, decoder: Any = None, correction_mask_fn: Any = None, loss_mask_fn: Any = None, baseline: Any = None, top_k: Any = 10, aggregate_hotspots: Any = True) -> Any: ...
    def estimate_default(self, /, shots: Any, seed: Any = None, baseline: Any = None, top_k: Any = 10) -> Any: ...
    def estimate_hotspots(self, /, batch: Any, loss_mask: Any, baseline: Any = None, top_k: Any = 10) -> Any: ...
    def run_batch(self, /, *, shots: Any, rng: Any = None, seed: Any = None, return_edge_events: Any = True) -> Any: ...
    def run_native_batch(self, /, shots: Any, seed: Any = None) -> Any: ...
    def sample(self, /, shots: Any, seed: Any = None, rng: Any = None) -> Any: ...

@final
class DemHotspotEstimate:
    def __new__(cls, /, dem: Any, shots: Any, mean_loss: Any, baseline: Any, edge_sensitivities: Any, edge_hotspots: Any, sensitivities: Any, hotspots: Any, by_detector: Any, by_round: Any, by_gate: Any, by_operation: Any, locations: Any, detector_graph_hotspots: Any, top_edges_cache: Any = None, top_hotspots_cache: Any = None) -> Self: ...
    @property
    def baseline(self) -> Any: ...
    @property
    def by_detector(self) -> Any: ...
    @property
    def by_gate(self) -> Any: ...
    @property
    def by_operation(self) -> Any: ...
    @property
    def by_round(self) -> Any: ...
    @property
    def dem(self) -> Any: ...
    @property
    def detector_graph_hotspots(self) -> Any: ...
    @property
    def edge_hotspots(self) -> Any: ...
    @property
    def edge_sensitivities(self) -> Any: ...
    def hotspot_table(self, /, top_k: Any = 10) -> Any: ...
    @property
    def hotspots(self) -> Any: ...
    @property
    def locations(self) -> Any: ...
    @property
    def logical_failure_rate(self) -> Any: ...
    @property
    def mean_loss(self) -> Any: ...
    @property
    def sensitivities(self) -> Any: ...
    @property
    def shots(self) -> Any: ...
    def top_edges(self, /, top_k: Any = 10) -> Any: ...
    @property
    def top_edges_cache(self) -> Any: ...
    def top_hotspots(self, /, top_k: Any = 10) -> Any: ...
    @property
    def top_hotspots_cache(self) -> Any: ...

@final
class DemHotspotEstimator:
    def __new__(cls, /, dem: Any) -> Self: ...
    @property
    def dem(self) -> Any: ...
    def estimate(self, /, *, shots: Any, seed: Any = None, decoder: Any = None, correction_mask_fn: Any = None, loss_mask_fn: Any = None, baseline: Any = None, top_k: Any = 10, aggregate_hotspots: Any = True) -> Any: ...
    def run_batch(self, /, *, shots: Any, rng: Any = None, seed: Any = None, return_edge_events: Any = True) -> Any: ...

@final
class DemLocationHotspot:
    def __new__(cls, /, location_id: Any, sensitivity: Any, hotspot: Any, qubits: Any, tags: Any) -> Self: ...
    @property
    def hotspot(self) -> Any: ...
    @property
    def location_id(self) -> Any: ...
    @property
    def qubits(self) -> Any: ...
    @property
    def sensitivity(self) -> Any: ...
    @property
    def tags(self) -> Any: ...

@final
class DemLocationMetadata:
    def __new__(cls, /, id: Any, tags: Any, qubits: Any = None) -> Self: ...
    @property
    def id(self) -> Any: ...
    @property
    def qubits(self) -> Any: ...
    @property
    def tags(self) -> Any: ...

@final
class DemSampleBatch:
    def __new__(cls, /, shots: Any, all_mask: Any, detectors: Any, observables: Any, edge_event_masks: Any) -> Self: ...
    @property
    def all_mask(self) -> Any: ...
    def bit(self, /, mask: Any, shot: Any) -> Any: ...
    def detector_bit(self, /, detector_id: Any, shot: Any) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    def edge_event_bit(self, /, edge_index: Any, shot: Any) -> Any: ...
    @property
    def edge_event_masks(self) -> Any: ...
    def observable_bit(self, /, observable_id: Any, shot: Any) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def shots(self) -> Any: ...

@final
class Detector:
    def __new__(cls, /, id: Any, measurement_keys: Any, coords: Any = None) -> Self: ...
    @property
    def coords(self) -> Any: ...
    @property
    def id(self) -> Any: ...
    @property
    def measurement_keys(self) -> Any: ...

@final
class DetectorErrorEdge:
    def __new__(cls, /, probability: Any, detectors: Any, observables: Any, location_id: Any, event: Any, tags: Any = None) -> Self: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def event(self) -> Any: ...
    @property
    def location_id(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def probability(self) -> Any: ...
    @property
    def tags(self) -> Any: ...
    def to_dem_line(self, /) -> Any: ...

@final
class DetectorErrorModel:
    def __new__(cls, /, detectors: Any, observables: Any, edges: Any) -> Self: ...
    def compile_binary_linear_problem(self, /) -> Any: ...
    def compile_graphlike_problem(self, /, *, decomposition: Any = None) -> Any: ...
    def compile_indexed(self, /) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def edges(self) -> Any: ...
    def edges_by_location(self, /) -> Any: ...
    def is_graphlike(self, /) -> Any: ...
    @property
    def observables(self) -> Any: ...
    def project_hotspots_to_edges(self, /, hotspots: Any) -> Any: ...
    def project_result_to_detector_graph(self, /, result: Any) -> Any: ...
    def project_sensitivities_to_detector_graph(self, /, sensitivities: Any) -> Any: ...
    def to_dem_text(self, /, *, include_detector_coords: Any = True) -> Any: ...

@final
class DetectorErrorModelGenerator:
    def __new__(cls, /, circuit: Any, *, detectors: Any = None, observables: Any = None, approximate_disjoint_errors: Any = 0.0) -> Self: ...
    @property
    def circuit(self) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    def generate(self, /) -> Any: ...
    def generate_artifact(self, /) -> Any: ...
    @property
    def observables(self) -> Any: ...

@final
class DetectorGraphEdgeHotspot:
    def __new__(cls, /, edge_index: Any, location_id: Any, event: Any, probability: Any, detectors: Any, observables: Any, sensitivity: Any, hotspot: Any, weight: Any) -> Self: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def edge_index(self) -> Any: ...
    @property
    def event(self) -> Any: ...
    @property
    def hotspot(self) -> Any: ...
    @property
    def location_id(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def probability(self) -> Any: ...
    @property
    def sensitivity(self) -> Any: ...
    @property
    def weight(self) -> Any: ...

@final
class DetectorGraphHotspots:
    def __new__(cls, /, edge_hotspots: Any, by_detector_edge: Any, signed_by_detector_edge: Any, by_detector: Any, signed_by_detector: Any, by_observable: Any, signed_by_observable: Any, by_location: Any, signed_by_location: Any) -> Self: ...
    @property
    def by_detector(self) -> Any: ...
    @property
    def by_detector_edge(self) -> Any: ...
    @property
    def by_location(self) -> Any: ...
    @property
    def by_observable(self) -> Any: ...
    @property
    def edge_hotspots(self) -> Any: ...
    def edge_table(self, /, top_k: Any = 10) -> Any: ...
    @property
    def signed_by_detector(self) -> Any: ...
    @property
    def signed_by_detector_edge(self) -> Any: ...
    @property
    def signed_by_location(self) -> Any: ...
    @property
    def signed_by_observable(self) -> Any: ...
    def top_edges(self, /, top_k: Any = 10) -> Any: ...

@final
class FailureEstimate:
    def __new__(cls, /, shots: Any, mean_loss: Any, baseline: Any, sensitivities: Any, hotspots: Any, by_qubit: Any, by_round: Any, by_gate: Any, by_operation: Any, locations: Any, losses: Any, top_hotspots_cache: Any = None) -> Self: ...
    @property
    def baseline(self) -> Any: ...
    @property
    def by_gate(self) -> Any: ...
    @property
    def by_operation(self) -> Any: ...
    @property
    def by_qubit(self) -> Any: ...
    @property
    def by_round(self) -> Any: ...
    def hotspot_table(self, /, top_k: Any = 10) -> Any: ...
    @property
    def hotspots(self) -> Any: ...
    @property
    def locations(self) -> Any: ...
    @property
    def logical_failure_rate(self) -> Any: ...
    @property
    def losses(self) -> Any: ...
    @property
    def mean_loss(self) -> Any: ...
    @property
    def sensitivities(self) -> Any: ...
    @property
    def shots(self) -> Any: ...
    def top_hotspots(self, /, top_k: Any = 10) -> Any: ...
    @property
    def top_hotspots_cache(self) -> Any: ...

@final
class FaultHotspot:
    def __new__(cls, /, location_id: Any, sensitivity: Any, hotspot: Any, qubits: Any, tags: Any) -> Self: ...
    @property
    def hotspot(self) -> Any: ...
    @property
    def location_id(self) -> Any: ...
    @property
    def qubits(self) -> Any: ...
    @property
    def sensitivity(self) -> Any: ...
    @property
    def tags(self) -> Any: ...

@final
class FaultScopeSimulator:
    def __new__(cls, /, circuit: Any, *, observables: Any = None) -> Self: ...
    @property
    def circuit(self) -> Any: ...
    def estimate(self, /, *, shots: Any, loss_mask_fn: Any = None, decoder: Any = None, correction_mask_fn: Any = None, seed: Any = None, baseline: Any = None, top_k: Any = 10) -> Any: ...
    @property
    def locations(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    def run_batch(self, /, *, shots: Any, rng: Any = None, seed: Any = None) -> Any: ...
    def sample(self, /, shots: Any, seed: Any = None, rng: Any = None) -> Any: ...
    def sample_measurements(self, /, shots: Any, seed: Any = None, rng: Any = None) -> Any: ...

@final
class GeneratedDetectorErrorModel:
    def __new__(cls, /, dem: Any, *, graphlike_hints: Any = None) -> Self: ...
    def compile_graphlike_problem(self, /) -> Any: ...
    @property
    def dem(self) -> Any: ...
    @property
    def graphlike_hints(self) -> Any: ...

@final
class GraphlikeDecodingProblem:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def detector_coords(self) -> Any: ...
    @property
    def detector_count(self) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    @property
    def edge_summary(self) -> Any: ...
    @property
    def edges(self) -> Any: ...
    @property
    def observable_count(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...

@final
class GraphlikeDecompositionHints:
    def __new__(cls, /, dem: Any, components_by_edge: Any) -> Self: ...
    @property
    def components_by_edge(self) -> Any: ...

@final
class GraphlikeEdge:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def dem_edge_index(self) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def fault_observables(self) -> Any: ...
    @property
    def probability(self) -> Any: ...
    @property
    def weight(self) -> Any: ...

@final
class IndexedDem:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def detector_coords(self) -> Any: ...
    @property
    def detector_count(self) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    @property
    def edge_summary(self) -> Any: ...
    @property
    def edges(self) -> Any: ...
    @property
    def observable_count(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...

@final
class IndexedDemEdge:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def detectors(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def original_edge_index(self) -> Any: ...
    @property
    def probability(self) -> Any: ...
    @property
    def weight(self) -> Any: ...

@final
class LogicalObservable:
    def __new__(cls, /, id: Any, measurement_keys: Any = None, pauli_qubits: Any = None, pauli: Any = '') -> Self: ...
    @property
    def id(self) -> Any: ...
    @property
    def measurement_keys(self) -> Any: ...
    @property
    def pauli(self) -> Any: ...
    @property
    def pauli_qubits(self) -> Any: ...

@final
class MeasurementBitFlip:
    def __new__(cls, /) -> Self: ...
    def apply(self, /, event: Any, state: Any, frame: Any, qubits: Any) -> Any: ...
    def apply_to_bit(self, /, bit: Any, event: Any) -> Any: ...
    def sample(self, /, rng: Any, rate: Any) -> Any: ...
    def score(self, /, event: Any, rate: Any) -> Any: ...

NATIVE_DECODER_PLUGIN_ABI: str
NATIVE_DECODER_PLUGIN_ABI_VERSION: int
NATIVE_DECODER_PLUGIN_CAPSULE_METHOD: str
NATIVE_DECODER_PLUGIN_CAPSULE_NAME: str
NATIVE_DECODER_PLUGIN_ENTRY_POINT_GROUP: str
NATIVE_GRAPHLIKE_PROBLEM_ABI: str
NATIVE_GRAPHLIKE_PROBLEM_ABI_VERSION: int
NATIVE_GRAPHLIKE_PROBLEM_CAPSULE_METHOD: str
NATIVE_GRAPHLIKE_PROBLEM_CAPSULE_NAME: str
@final
class NativeBatchDecoder:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    def decode_batch_masks(self, /, batch: Any) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @staticmethod
    def no_correction(observable_ids: Any = None, detector_ids: Any = None) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def python_decode_call_count(self) -> Any: ...
    def strong_id_payload(self, /) -> Any: ...

@final
class NativeCompositeDecoder:
    def __new__(cls, /, decoders: Any) -> Self: ...
    def decode_batch_masks(self, /, batch: Any) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def python_decode_call_count(self) -> Any: ...
    def strong_id_payload(self, /) -> Any: ...

@final
class NativeDemBatch:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def all_mask(self) -> Any: ...
    def bit(self, /, mask: Any, shot: Any) -> Any: ...
    def detector_bit(self, /, detector_id: Any, shot: Any) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    def edge_event_bit(self, /, edge_index: Any, shot: Any) -> Any: ...
    @property
    def edge_event_masks(self) -> Any: ...
    def observable_bit(self, /, observable_id: Any, shot: Any) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def shots(self) -> Any: ...

@final
class NativeDemGenerator:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    def compile_sampler(self, /, *, materialize_dem: Any = True) -> Any: ...
    def generate(self, /) -> Any: ...
    def generate_artifact(self, /) -> Any: ...
    def generate_dem(self, /) -> Any: ...

@final
class NativeDemSampler:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def dem(self) -> Any: ...
    @property
    def edge_count(self) -> Any: ...
    def estimate(self, /, shots: Any, seed: Any = None, decoder: Any = None, correction_mask_fn: Any = None, loss_mask_fn: Any = None, baseline: Any = None, top_k: Any = 10, aggregate_hotspots: Any = True) -> Any: ...
    def estimate_default(self, /, shots: Any, seed: Any = None, baseline: Any = None, top_k: Any = 10) -> Any: ...
    def estimate_hotspots(self, /, batch: Any, loss_mask: Any, baseline: Any = None, top_k: Any = 10) -> Any: ...
    def require_dem_metadata(self, /) -> Any: ...
    def run_batch(self, /, shots: Any, seed: Any = None, return_edge_events: Any = True, rng: Any = None) -> Any: ...
    def run_native_batch(self, /, shots: Any, seed: Any = None) -> Any: ...

@final
class NativeGraphlikeDetectorCopyDecoder:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    def decode_batch_masks(self, /, batch: Any) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @staticmethod
    def from_circuit(circuit: Any, *, detectors: Any = None, observables: Any = None) -> Any: ...
    @staticmethod
    def from_dem(dem: Any) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def python_decode_call_count(self) -> Any: ...
    def strong_id_payload(self, /) -> Any: ...

@final
class NativeNoCorrectionDecoder:
    def __new__(cls, /, observable_ids: Any = None, detector_ids: Any = None) -> Self: ...
    def decode_batch_masks(self, /, batch: Any) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    @staticmethod
    def from_circuit(circuit: Any, *, detectors: Any = None, observables: Any = None) -> Any: ...
    @property
    def name(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def python_decode_call_count(self) -> Any: ...
    def strong_id_payload(self, /) -> Any: ...

@final
class NativePackedBatch:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def all_mask(self) -> Any: ...
    def bit(self, /, mask: Any, shot: Any) -> Any: ...
    def detector_bit(self, /, detector_id: Any, shot: Any) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    def measurement_bit(self, /, key: Any, shot: Any) -> Any: ...
    def measurement_mask(self, /, key: Any) -> Any: ...
    def measurement_masks(self, /, keys: Any) -> Any: ...
    @property
    def measurements(self) -> Any: ...
    @property
    def noise_event_masks(self) -> Any: ...
    def observable_bit(self, /, observable_id: Any, shot: Any) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def shots(self) -> Any: ...
    def x_bit(self, /, qubit: Any, shot: Any) -> Any: ...
    @property
    def x_frame(self) -> Any: ...
    def x_mask(self, /, qubit: Any) -> Any: ...
    def z_bit(self, /, qubit: Any, shot: Any) -> Any: ...
    @property
    def z_frame(self) -> Any: ...
    def z_mask(self, /, qubit: Any) -> Any: ...

@final
class NativePackedSampler:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def circuit(self) -> Any: ...
    @property
    def detector_ids(self) -> Any: ...
    def estimate(self, /, shots: Any, loss_mask_fn: Any = None, decoder: Any = None, correction_mask_fn: Any = None, seed: Any = None, baseline: Any = None, top_k: Any = 10) -> Any: ...
    def estimate_hotspots(self, /, batch: Any, loss_mask: Any, baseline: Any = None, top_k: Any = 10) -> Any: ...
    @property
    def loop_kernel_count(self) -> Any: ...
    @property
    def n_qubits(self) -> Any: ...
    @property
    def observable_ids(self) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def operation_count(self) -> Any: ...
    def run_native_batch(self, /, shots: Any, seed: Any = None) -> Any: ...
    def sample(self, /, shots: Any, seed: Any = None, rng: Any = None) -> Any: ...
    def sample_measurements(self, /, shots: Any, seed: Any = None, rng: Any = None) -> Any: ...
    @property
    def stored_operation_count(self) -> Any: ...

@final
class NoiseLocation:
    def __new__(cls, /, id: Any, model: Any, rate: Any, qubits: Any, tags: Any = None) -> Self: ...
    @property
    def id(self) -> Any: ...
    @property
    def model(self) -> Any: ...
    @property
    def qubits(self) -> Any: ...
    @property
    def rate(self) -> Any: ...
    @property
    def tags(self) -> Any: ...

@final
class Operation:
    def __new__(cls, /, kind: Any, qubits: Any = None, key: Any = None, basis: Any = None, pauli: Any = None, measurement_keys: Any = None, observable_id: Any = None, noise_location: Any = None, metadata: Any = None) -> Self: ...
    @property
    def basis(self) -> Any: ...
    @property
    def body(self) -> Any: ...
    @staticmethod
    def cx(control: Any, target: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def cz(left: Any, right: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def detector(measurement_keys: Any, *, detector_id: Any = None, coords: Any = None, **metadata: Any) -> Any: ...
    @staticmethod
    def detector_rec(lookbacks: Any, *, detector_id: Any = None, coords: Any = None, **metadata: Any) -> Any: ...
    @staticmethod
    def h(qubit: Any, **metadata: Any) -> Any: ...
    @property
    def key(self) -> Any: ...
    @property
    def kind(self) -> Any: ...
    @staticmethod
    def measure(qubit: Any, *, key: Any = None, basis: Any = 'Z', noise: Any = None, **metadata: Any) -> Any: ...
    @staticmethod
    def measure_pauli(qubits: Any, pauli: Any, *, key: Any = None, noise: Any = None, **metadata: Any) -> Any: ...
    @staticmethod
    def measure_reset(qubit: Any, *, basis: Any = 'Z', **metadata: Any) -> Any: ...
    @property
    def measurement_keys(self) -> Any: ...
    @property
    def metadata(self) -> Any: ...
    @staticmethod
    def noise(location: Any, **metadata: Any) -> Any: ...
    @property
    def noise_location(self) -> Any: ...
    @property
    def observable_id(self) -> Any: ...
    @staticmethod
    def observable_include(observable_id: Any, measurement_keys: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def observable_include_rec(observable_id: Any, lookbacks: Any, **metadata: Any) -> Any: ...
    @property
    def pauli(self) -> Any: ...
    @staticmethod
    def pauli_gate(qubits: Any, pauli: Any, **metadata: Any) -> Any: ...
    @property
    def qubits(self) -> Any: ...
    @property
    def record_lookbacks(self) -> Any: ...
    @staticmethod
    def repeat(count: Any, operations: Any, **metadata: Any) -> Any: ...
    @property
    def repeat_count(self) -> Any: ...
    @staticmethod
    def reset(qubit: Any, *, key: Any = None, basis: Any = 'Z', **metadata: Any) -> Any: ...
    @staticmethod
    def s(qubit: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def s_dag(qubit: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def shift_coords(offsets: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def swap(left: Any, right: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def tick(**metadata: Any) -> Any: ...
    @staticmethod
    def x(qubit: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def y(qubit: Any, **metadata: Any) -> Any: ...
    @staticmethod
    def z(qubit: Any, **metadata: Any) -> Any: ...

@final
class PauliChannel:
    def __new__(cls, /, weights: Any) -> Self: ...
    def apply(self, /, event: Any, state: Any, frame: Any, qubits: Any) -> Any: ...
    @property
    def event_length(self) -> Any: ...
    def sample(self, /, rng: Any, rate: Any) -> Any: ...
    def score(self, /, event: Any, rate: Any) -> Any: ...
    @property
    def total_weight(self) -> Any: ...
    @property
    def weights(self) -> Any: ...

@final
class PauliFrame:
    def __new__(cls, /, x: Any, z: Any) -> Self: ...
    def apply_cx(self, /, control: Any, target: Any) -> Any: ...
    def apply_cz(self, /, left: Any, right: Any) -> Any: ...
    def apply_h(self, /, qubit: Any) -> Any: ...
    def apply_pauli(self, /, qubit: Any, pauli: Any) -> Any: ...
    def apply_pauli_string(self, /, qubits: Any, paulis: Any) -> Any: ...
    def apply_s(self, /, qubit: Any) -> Any: ...
    def apply_s_dag(self, /, qubit: Any) -> Any: ...
    def apply_swap(self, /, left: Any, right: Any) -> Any: ...
    def copy(self, /) -> Any: ...
    def measurement_flip(self, /, qubits: Any, paulis: Any) -> Any: ...
    @property
    def n_qubits(self) -> Any: ...
    def pauli_on(self, /, qubits: Any) -> Any: ...
    def reset(self, /, qubit: Any) -> Any: ...
    @property
    def x(self) -> Any: ...
    @property
    def z(self) -> Any: ...
    @staticmethod
    def zero(n_qubits: Any) -> Any: ...

@final
class SampleBatch:
    def __new__(cls, /, shots: Any, all_mask: Any, x_frame: Any, z_frame: Any, measurements: Any, detectors: Any, observables: Any, noise_event_masks: Any) -> Self: ...
    @property
    def all_mask(self) -> Any: ...
    def bit(self, /, mask: Any, shot: Any) -> Any: ...
    def detector_bit(self, /, detector_id: Any, shot: Any) -> Any: ...
    @property
    def detectors(self) -> Any: ...
    def measurement_bit(self, /, key: Any, shot: Any) -> Any: ...
    def measurement_mask(self, /, key: Any) -> Any: ...
    @property
    def measurements(self) -> Any: ...
    @property
    def noise_event_masks(self) -> Any: ...
    def observable_bit(self, /, observable_id: Any, shot: Any) -> Any: ...
    @property
    def observables(self) -> Any: ...
    @property
    def shots(self) -> Any: ...
    def x_bit(self, /, qubit: Any, shot: Any) -> Any: ...
    @property
    def x_frame(self) -> Any: ...
    def x_mask(self, /, qubit: Any) -> Any: ...
    def z_bit(self, /, qubit: Any, shot: Any) -> Any: ...
    @property
    def z_frame(self) -> Any: ...
    def z_mask(self, /, qubit: Any) -> Any: ...

@final
class SingleQubitDepolarizing:
    def __new__(cls, /) -> Self: ...
    def apply(self, /, event: Any, state: Any, frame: Any, qubits: Any) -> Any: ...
    def sample(self, /, rng: Any, rate: Any) -> Any: ...
    def score(self, /, event: Any, rate: Any) -> Any: ...

@final
class SparseBinaryMatrix:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    @property
    def col_count(self) -> Any: ...
    @property
    def entries(self) -> Any: ...
    @property
    def entry_count(self) -> Any: ...
    @property
    def row_count(self) -> Any: ...

@final
class StabilizerState:
    def __new__(cls, _no_direct_construction: Never, /) -> Self: ...
    def apply_cx(self, /, control: Any, target: Any) -> Any: ...
    def apply_cz(self, /, left: Any, right: Any) -> Any: ...
    def apply_h(self, /, qubit: Any) -> Any: ...
    def apply_pauli(self, /, qubit: Any, pauli: Any) -> Any: ...
    def apply_pauli_string(self, /, x: Any, z: Any = None) -> Any: ...
    def apply_s(self, /, qubit: Any) -> Any: ...
    def apply_s_dag(self, /, qubit: Any) -> Any: ...
    def apply_swap(self, /, left: Any, right: Any) -> Any: ...
    def copy(self, /) -> Any: ...
    def deterministic_measurement_bit(self, /, x: Any, z: Any) -> Any: ...
    def is_deterministic_pauli(self, /, x: Any, z: Any) -> Any: ...
    def measure_pauli(self, /, x: Any, z: Any, rng: Any) -> Any: ...
    def measure_x(self, /, qubit: Any, rng: Any) -> Any: ...
    def measure_y(self, /, qubit: Any, rng: Any) -> Any: ...
    def measure_z(self, /, qubit: Any, rng: Any) -> Any: ...
    @property
    def n_qubits(self) -> Any: ...
    def reset_x(self, /, qubit: Any, rng: Any) -> Any: ...
    def reset_y(self, /, qubit: Any, rng: Any) -> Any: ...
    def reset_z(self, /, qubit: Any, rng: Any) -> Any: ...
    @property
    def sign(self) -> Any: ...
    @property
    def x(self) -> Any: ...
    @property
    def z(self) -> Any: ...
    @staticmethod
    def zero(n_qubits: Any) -> Any: ...

@final
class TwoQubitDepolarizing:
    def __new__(cls, /, _events: Any = None) -> Self: ...
    def apply(self, /, event: Any, state: Any, frame: Any, qubits: Any) -> Any: ...
    def sample(self, /, rng: Any, rate: Any) -> Any: ...
    def score(self, /, event: Any, rate: Any) -> Any: ...

__version__: str
def _collect_dem_hotspots_many(tasks: Any, num_workers: Any = 1, seed: Any = None, count_observable_error_combos: Any = False, count_detection_events: Any = False, custom_error_count_key: Any = None) -> Any: ...
def _collect_dem_logical_error_stats_many(tasks: Any, num_workers: Any = 1, seed: Any = None, count_observable_error_combos: Any = False, count_detection_events: Any = False, custom_error_count_key: Any = None, existing_stats: Any = None, progress_callback: Any = None) -> Any: ...
def _collect_forward_hotspots_many(tasks: Any, num_workers: Any = 1, seed: Any = None, count_observable_error_combos: Any = False, count_detection_events: Any = False, custom_error_count_key: Any = None) -> Any: ...
def _collect_forward_logical_error_stats_many(tasks: Any, num_workers: Any = 1, seed: Any = None, count_observable_error_combos: Any = False, count_detection_events: Any = False, custom_error_count_key: Any = None, existing_stats: Any = None, progress_callback: Any = None) -> Any: ...
def available_native_decoders() -> Any: ...
def compile_collection_sampler(circuit: Any, detectors: Any = None, observables: Any = None) -> Any: ...
def compile_dem_generator(circuit: Any, detectors: Any = None, observables: Any = None, *, approximate_disjoint_errors: Any = 0.0) -> Any: ...
def compile_dem_sampler(dem: Any) -> Any: ...
def compile_generated_dem_sampler(circuit: Any, detectors: Any = None, observables: Any = None, *, approximate_disjoint_errors: Any = 0.0) -> Any: ...
def compile_sampler(circuit: Any, observables: Any = None) -> Any: ...
def generate_and_compile_dem_sampler(circuit: Any, detectors: Any = None, observables: Any = None, *, approximate_disjoint_errors: Any = 0.0) -> Any: ...
def generate_dem(circuit: Any, detectors: Any, observables: Any, *, approximate_disjoint_errors: Any = 0.0) -> Any: ...
