[package]
name = "npsim-python"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_npsim_native"
crate-type = ["cdylib"]
test = false

[features]
default = []
decoder-fusion-blossom = ["npsim-core/decoder-fusion-blossom"]
decoder-bposd = ["npsim-core/decoder-bposd"]

[dependencies]
npsim-core = { path = "../npsim-core" }
pyo3 = { version = "0.23", features = ["extension-module"] }

[package.metadata.maturin]
module-name = "npsim._npsim_native"
python-source = "../.."
